background_image_url:
  type: upload
  default: ""
  description: Background image for the site chrome.

banner_image_url:
  type: upload
  default: ""
  description: Optional background image for header/banner sections.

enable_brand_header:
  type: bool
  default: true
  description: Show logo label and brand overrides in the header.

brand_logo_url:
  type: upload
  default: ""
  description: Optional brand logo image used in the header when brand header is enabled.

header_label_text:
  type: string
  default: "Collaborate. Document. Grow."
  description: Small tagline after the site logo (e.g., "Collaborate. Document. Grow.").

enable_header_quotes:
  type: bool
  default: true
  description: Show the rotating quotes banner below the header.

show_banner_on_homepage:
  type: bool
  default: true
  description: Show banner on the homepage/categories page.

show_banner_on_topics:
  type: bool
  default: true
  description: Show banner on topic list pages (latest, top, etc).

show_banner_on_topic_view:
  type: bool
  default: false
  description: Show banner when viewing individual topics.

show_banner_on_admin:
  type: bool
  default: false
  description: Show banner on admin pages.

glass_blur_amount:
  type: string
  default: "12px"
  description: CSS blur for glass panels (e.g., 8px, 12px).

login_background_image_url:
  type: upload
  default: ""
  description: Background image for the left panel in the login modal.

show_banner_on_login:
  type: bool
  default: true
  description: Show the quotes banner on the login page.

# Category card titles and subtitles
hero_card_1_label:
  type: string
  default: "Knowledge Base"
  description: "Title for category card 1"

hero_card_1_subtitle:
  type: string
  default: "Vendor Manuals, Specs & Docs"
  description: "Subtitle/description for category card 1"

hero_card_1_url:
  type: string
  default: "/c/knowledge-base/5"
  description: "URL for category card 1"

hero_card_2_label:
  type: string
  default: "Tech Community"
  description: "Title for category card 2"

hero_card_2_subtitle:
  type: string
  default: "Ask Questions & Share Expertise"
  description: "Subtitle/description for category card 2"

hero_card_2_url:
  type: string
  default: "/c/tech-community/4"
  description: "URL for category card 2"

hero_card_3_label:
  type: string
  default: "How-To & Troubleshooting"
  description: "Title for category card 3"

hero_card_3_subtitle:
  type: string
  default: "Guides, Tutorials & Fixes"
  description: "Subtitle/description for category card 3"

hero_card_3_url:
  type: string
  default: "/c/how-to/6"
  description: "URL for category card 3"

hero_card_4_label:
  type: string
  default: "AI Assistant (AME-Bot)"
  description: "Title for category card 4"

hero_card_4_subtitle:
  type: string
  default: "Get Instant Answers"
  description: "Subtitle/description for category card 4"

hero_card_4_url:
  type: string
  default: "/search?q=category%3Aai-assistant"
  description: "URL for category card 4"

# Rotating quotes - format: "QUOTE TEXT|word1,word2,word3" where words after | are bolded
quote_1:
  type: string
  default: "ALONE WE CAN DO SO LITTLE; TOGETHER WE CAN DO MUCH.|ALONE,TOGETHER"
  description: "Quote 1: text|words-to-bold (comma separated)"

quote_2:
  type: string
  default: "KNOWLEDGE SHARED IS KNOWLEDGE SQUARED.|SHARED,SQUARED"
  description: "Quote 2: text|words-to-bold (comma separated)"

quote_3:
  type: string
  default: "RAISE THE FLOOR, THEN RAISE THE CEILING.|RAISE,FLOOR,CEILING"
  description: "Quote 3: text|words-to-bold (comma separated)"

quote_4:
  type: string
  default: "PUT KNOWLEDGE WHERE PEOPLE TRIP OVER IT.|KNOWLEDGE,TRIP"
  description: "Quote 4: text|words-to-bold (comma separated)"

quote_5:
  type: string
  default: "EVERYBODY IS SMARTER THAN ANYBODY.|EVERYBODY,SMARTER,ANYBODY"
  description: "Quote 5: text|words-to-bold (comma separated)"

quote_6:
  type: string
  default: "KNOWLEDGE IS LIKE MONEY: TO BE OF VALUE IT MUST CIRCULATE.|KNOWLEDGE,VALUE,CIRCULATE"
  description: "Quote 6: text|words-to-bold (comma separated)"

quote_7:
  type: string
  default: "THE BEST WAY TO PREDICT THE FUTURE IS TO INVENT IT.|PREDICT,FUTURE,INVENT"
  description: "Quote 7: text|words-to-bold (comma separated)"
