hero_image:
  type: upload
  default: ""
  description: Hero background image (building) used site‑wide

tech_overlay:
  type: upload
  default: ""
  description: Transparent SVG tech/circuit pattern

enable_particles:
  type: bool
  default: true
  description: Enable subtle HUD particles

brand_header_enabled:
  type: bool
  default: true
  description: Show brand header bar with rotating quotes

quotes:
  type: list
  default:
    - "Adapt. Evolve. Build."
    - "Ship fast, learn faster."
    - "Always improving."
  description: Rotating quotes shown in the brand header

# Optional font uploads (use if you want Aktiv Grotesk)
font_aktiv_rg:
  type: upload
  default: ""
font_aktiv_md:
  type: upload
  default: ""
font_aktiv_bd:
  type: upload
  default: ""
font_aktiv_ex:
  type: upload
  default: ""
